# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          foto_list/bin/Release/net6.0/
          mtest/bin/Release/net6.0/
        if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .
    
    - name: Install coverage tool
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet tool list --global
    
    - name: Test with coverage
      run: |
        dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage
        echo "Coverage directory contents:"
        ls -la ./coverage
        echo "Coverage files:"
        find ./coverage -name "*.coverage" -type f
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: ./coverage/**/*.coverage
        if-no-files-found: error

  package:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./artifacts
    
    - name: Download coverage reports
      uses: actions/download-artifact@v4
      with:
        name: coverage-reports
        path: ./coverage
    
    - name: Create release package
      run: |
        mkdir -p ./release
        cp -r ./artifacts/* ./release/
        cp -r ./coverage ./release/
    
    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: ./release
        if-no-files-found: error
